language: node_js
node_js:
- '8'
cache: yarn
script:
- yarn --version
- yarn check --integrity
- yarn test
deploy:
  provider: npm
  email: jenkins-reform@HMCTS.NET
  api_key:
    secure: UeKKWCSQEKhVZD8v+b08J5IpPISYnoP6C04/S8SeUOua1YTWFaqPF7BSJe/2cu9ewuBElV79iXp5RnEWUknuTQdQN+dyGBLeIMCZe3v/aPDen1BXaoro4QG3nAgdAwlO/hQH2qNcrXBmogJp0OjYfalesUU6v9DEgd6SwpFeducCLDW9A3EAWbAoMFKAUTr6AeP4/SYiLmNEqDMcAC/VE9g84sqlnxwumhYLLF4dCpsz63OZotU9ecLHJA3yFe1v3rt1+ANAcdxGMzMS2Dbj+eADQ7CqWMLOErcmtMT82rQo+36E1dLmDwMj8wBCOc2IavW7fsiy/79rK25Cp1mxRecCB8+jj4um6yPyGLHUnyCyAKyzZRXhzmTIhIFi/rt1ZaeaIbJav7hD/guDDcMFsiRBpluRPeRb78lz1bFo8Uw7NQdiEl2S5ENOMUZzNlbkGJgiKWhgG243pr487csbZDsAaywgjVA07wb6EdkttrpFz7iyxqrQwYlS5ZbS6hBddtl2nD74VwAQ7fLPpzRYJTKghEojjO7ksApdf7yJb1pOz26DKCeNotSKHdTbnq/tLV/id4F0FcefeDzgIm1HEzFJLGl/R9kRCSBaGAu683LI+dubKHacRYCYGimQwc2/REchD8zgYA7HfeXgvVyJaHKarXdL/2fNNeyw9+BAr80=
  on:
    tags: true
    repo: hmcts/div-document-express-handler
